export const projectsData = [
  {
    id: 1,
    name: "shaadmani",
    title: "Shaadmani Web App",
    description: " Streamlined matchmaking platform",
    image: "/images/projects/3.png",
    tag: ["All", "Web"],
    gitUrl: "/",
    previewUrl: "/",
    technologies: [
      "ri:nextjs-fill",
      "skill-icons:tailwindcss-light",
      "skill-icons:expressjs-dark",
      "logos:nodejs-icon",
      "devicon:mongodb",
    ],
  },
  {
    id: 2,
    name: "nearme",
    title: "NearMe Web App",
    description: "Online E-Commerce Shopping website",
    image: "/images/projects/4.png",
    tag: ["All", "Mobile"],
    gitUrl: "/",
    previewUrl: "/",
    technologies: [
      "ri:nextjs-fill",
      "skill-icons:tailwindcss-light",
      "skill-icons:expressjs-dark",
      "logos:nodejs-icon",
      "devicon:mongodb",
    ],
  },
  {
    id: 3,
    name: "menatcp",
    title: "MenaTcp Web App",
    description: "MenaTCP Educational Accademy and Dashbaord Panel",
    image: "/images/projects/5.png",
    tag: ["All", "Web"],
    gitUrl: "/",
    previewUrl: "/",
    technologies: [
      "ri:nextjs-fill",
      "skill-icons:tailwindcss-light",
      "skill-icons:expressjs-dark",
      "logos:nodejs-icon",
      "devicon:mongodb",
      "skill-icons:gcp-light",
    ],
  },
  {
    id: 4,
    name: "graphit",
    title: "Graphit Web App",
    description: "AI Image Generator Platform",
    image: "/images/projects/graphit.png",
    tag: ["All", "Web"],
    gitUrl: "/",
    previewUrl: "https://www.ridagilani.me/",
    technologies: [
      "ri:nextjs-fill",
      "skill-icons:tailwindcss-light",
      "skill-icons:expressjs-dark",
      "logos:nodejs-icon",
      "devicon:mongodb",
      "skill-icons:gcp-light",
    ],
  },
  {
    id: 5,
    name: "harpy",
    title: "Harpy Commerce",
    description: "IT Company Portfolio Website",
    image: "/images/projects/harpy.PNG",
    tag: ["All", "Web"],
    gitUrl: "/",
    previewUrl: "https://www.ridagilani.me/",
    technologies: [
      "skill-icons:wordpress",
      "simple-icons:elementor",
      "majesticons:mail",
    ],
  },
  {
    id: 6,
    name: "limo",
    title: "Limo Dashboard Pannel",
    description: "Online Car Booking System",
    image: "/images/projects/limo.png",
    tag: ["All", "Web"],
    gitUrl: "/",
    previewUrl: "https://www.ridagilani.me/",
    technologies: [
      "ri:nextjs-fill",
      "skill-icons:tailwindcss-light",
      "skill-icons:expressjs-dark",
      "logos:nodejs-icon",
      "devicon:mongodb",
      "skill-icons:gcp-light",
    ],
  },
];

export const caseStudies = [
  { name: "shaadmani", picture: ["/images/casestudy.png"] },
  {
    name: "menatcp",
    picture: [
      "/images/casestudymena.png",
      "/images/casestudy.png",
      "/images/mena3.png",
    ],
  },
  { name: "limo", picture: ["/images/casestudy.png"] },
  { name: "nearme", picture: ["/images/casestudy.png"] },
  { name: "harpy", picture: ["/images/casestudy.png"] },
  { name: "graphit", picture: ["/images/casestudy.png"] },
];
