export const projectsData = [
  {
    id: 1,
    name: "expert",
    title: "Expert Web App",
    description: "Expert Consulting Services Platform",
    image: "/images/projects/expert.PNG",
    tag: ["All", "Web"],
    gitUrl: "/",
    previewUrl: "https://expert.one/",
    technologies: [
      "ri:nextjs-fill",
      "skill-icons:tailwindcss-light",
      "skill-icons:expressjs-dark",
      "logos:nodejs-icon",
      "devicon:mongodb",
      "skill-icons:gcp-light",
    ],
  },
  {
    id: 2,
    name: "superfood",
    title: "SuperFoodLx Web App",
    description: "SuperFoodLx - Natural Hair Growth and Wellness Products",
    image: "/images/projects/superlx.PNG",
    tag: ["All", "Web"],
    gitUrl: "/",
    previewUrl: "https://superfoodlx.com/",
    technologies: [
      "ri:nextjs-fill",
      "skill-icons:tailwindcss-light",
      "skill-icons:expressjs-dark",
      "logos:nodejs-icon",
      "devicon:mongodb",
      "skill-icons:gcp-light",
    ],
  },
  {
    id: 3,
    name: "nearme",
    title: "NearMe Web App",
    description: "Online E-Commerce Shopping website",
    image: "/images/projects/4.png",
    tag: ["All", "Mobile"],
    gitUrl: "/",
    previewUrl: "/",
    technologies: [
      "ri:nextjs-fill",
      "skill-icons:tailwindcss-light",
      "skill-icons:expressjs-dark",
      "logos:nodejs-icon",
      "devicon:mongodb",
    ],
  },
  {
    id: 4,
    name: "menatcp",
    title: "MenaTcp Web App",
    description: "MenaTCP Educational Accademy and Dashbaord Panel",
    image: "/images/projects/5.png",
    tag: ["All", "Web"],
    gitUrl: "https://menatcp.com/",
    previewUrl: "https://menatcp.com/",
    technologies: [
      "ri:nextjs-fill",
      "skill-icons:tailwindcss-light",
      "skill-icons:expressjs-dark",
      "logos:nodejs-icon",
      "devicon:mongodb",
      "skill-icons:gcp-light",
    ],
  },
  {
    id: 5,
    name: "graphit",
    title: "Graphit Web App",
    description: "AI Image Generator Platform",
    image: "/images/projects/graphit.png",
    tag: ["All", "Web"],
    gitUrl: "/",
    previewUrl: "",
    technologies: [
      "ri:nextjs-fill",
      "skill-icons:tailwindcss-light",
      "skill-icons:expressjs-dark",
      "logos:nodejs-icon",
      "devicon:mongodb",
      "skill-icons:gcp-light",
    ],
  },
  {
    id: 6,
    name: "harpy",
    title: "Harpy Commerce",
    description: "IT Company Portfolio Website",
    image: "/images/projects/harpy.PNG",
    tag: ["All", "Web"],
    gitUrl: "/",
    previewUrl: "",
    technologies: [
      "skill-icons:wordpress",
      "simple-icons:elementor",
      "majesticons:mail",
    ],
  },
  {
    id: 7,
    name: "limo",
    title: "Limo Dashboard Pannel",
    description: "Online Car Booking System",
    image: "/images/projects/limo.png",
    tag: ["All", "Web"],
    gitUrl: "/",
    previewUrl: "",
    technologies: [
      "ri:nextjs-fill",
      "skill-icons:tailwindcss-light",
      "skill-icons:expressjs-dark",
      "logos:nodejs-icon",
      "devicon:mongodb",
      "skill-icons:gcp-light",
    ],
  },
  {
    id: 8,
    name: "plexaar",
    title: "Plexaar",
    description: "Calendex - Online Appointment and Service Booking Platform",
    image: "/images/projects/plexaar.PNG",
    tag: ["All", "Web"],
    gitUrl: "/",
    previewUrl: "https://calendex.plexaar.com/",
    technologies: [
      "ri:nextjs-fill",
      "skill-icons:tailwindcss-light",
      "skill-icons:expressjs-dark",
      "logos:nodejs-icon",
      "devicon:mongodb",
      "skill-icons:gcp-light",
    ],
  },
  {
    id: 9,
    name: "homesetv",
    title: "Home SeTV",
    description:
      "Home SeTv - Enhancing Remote Communication with Virtual Studios and Digital Environments",
    image: "/images/projects/homesetv.PNG",
    tag: ["All", "Web"],
    gitUrl: "/",
    previewUrl: "https://www.homesetv.it/eng/main/",
    technologies: [
      "ri:nextjs-fill",
      "skill-icons:tailwindcss-light",
      "skill-icons:expressjs-dark",
      "logos:nodejs-icon",
      "devicon:mongodb",
      "skill-icons:gcp-light",
    ],
  },

  {
    id: 10,
    name: "gelEnergy",
    title: "Gel Energy",
    description: "Gel Energy - Solar Panels & Renewable Energy Solutions",
    image: "/images/projects/gelenergy.PNG",
    tag: ["All", "Web"],
    gitUrl: "/",
    previewUrl: "https://gelenergy.co.za/",
    technologies: [
      "ri:nextjs-fill",
      "skill-icons:tailwindcss-light",
      "skill-icons:expressjs-dark",
      "logos:nodejs-icon",
      "devicon:mongodb",
      "skill-icons:gcp-light",
    ],
  },
  {
    id: 11,
    name: "steelPallet",
    title: "Steel Pallet",
    description: "Gel Energy - Solar Panels & Renewable Energy Solutions",
    image: "/images/projects/steel.PNG",
    tag: ["All", "Web"],
    gitUrl: "/",
    previewUrl: "https://www.steelpalletsusa.com/",
    technologies: [
      "ri:nextjs-fill",
      "skill-icons:tailwindcss-light",
      "skill-icons:expressjs-dark",
      "logos:nodejs-icon",
      "devicon:mongodb",
      "skill-icons:gcp-light",
    ],
  },

  {
    id: 12,
    name: "youtiva",
    title: "Youtiva",
    description: "Video Content Management Solutions",
    image: "/images/projects/youtiva.PNG",
    tag: ["All", "Web"],
    gitUrl: "/",
    previewUrl: "https://youtiva.com/",
    technologies: [
      "ri:nextjs-fill",
      "skill-icons:tailwindcss-light",
      "skill-icons:expressjs-dark",
      "logos:nodejs-icon",
      "devicon:mongodb",
      "skill-icons:gcp-light",
    ],
  },
  {
    id: 13,
    name: "shaadmani",
    title: "Shaadmani Web App",
    description: " Streamlined matchmaking platform",
    image: "/images/projects/3.png",
    tag: ["All", "Web"],
    gitUrl: "/",
    previewUrl: "/",
    technologies: [
      "ri:nextjs-fill",
      "skill-icons:tailwindcss-light",
      "skill-icons:expressjs-dark",
      "logos:nodejs-icon",
      "devicon:mongodb",
    ],
  },
];

export const caseStudies = [
  { name: "shaadmani", picture: ["/images/casestudy.png"] },
  {
    name: "menatcp",
    picture: ["/images/menatcp.jpg"],
  },
  { name: "limo", picture: ["/images/casestudy.png"] },
  { name: "nearme", picture: ["/images/casestudy.png"] },
  { name: "harpy", picture: ["/images/casestudy.png"] },
  { name: "graphit", picture: ["/images/graphit.jpg"] },
];
