"use client";
import { Suspense, useEffect, useState } from "react";
import Footer from "./components/Footer";
import Navbar from "./components/Navbar";
import "./globals.css";
import { Great_Vibes, Inter, Poppins } from "next/font/google";
import Loading from "./loading";
import { usePathname } from "next/navigation";
import SplashScreen from "./components/SplashScreen";

const inter = Inter({ subsets: ["latin"] });
const poppins = Poppins({
  weight: ["300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-poppins",
});
const greatVibes = Great_Vibes({
  weight: ["400"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-great_vibes",
});
// export const metadata = {
//   title: "Portfolio Website",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const pathname = usePathname();
  const isHome = pathname === "/";
  const [isLoading, setLoading] = useState(isHome);

  useEffect(() => {
    if (isLoading) return;
  }, [isLoading]);
  return (
    <html lang="en">
      <Suspense loading={<Loading />}>
        <body className={` bg-[#131313] ${poppins.className}`}>
          {isLoading ? (
            <SplashScreen
              greatVibesFont={greatVibes}
              finishLoading={() => setLoading(false)}
            />
          ) : (
            <>
              <Navbar font={greatVibes} />
              {children}
              <Footer font={greatVibes} />
            </>
          )}
        </body>
      </Suspense>
    </html>
  );
}
